version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    ports:
      - 3000:3000
    tty: true # コンテナの起動永続化
    volumes:
      - .:/usr/src/work
